### ISSUE TITLE
Problème avec Lambert 93

### ISSUE THREAD

**Issue by vinber** [riatelab/magrit#51] opened 2019-07-25 16:08 UTC
# Exemple 1

- un nouveau projet
- Sélection d'un fond de carte d'exemple (world_countries_data)
- dans le menu des projections, choisir plus d'options, lambert 93, reprojetter, confirmer,
- cela fonctionne parfaitement

# Exemple 2

- un nouveau projet
- Sélection d'un fond de carte d'exemple (world_countries_data)
- choisir lambert93
- et cela patine, même en laissant longtemps cela ne fonctionne pas

**Comment by rCarto** [comment] 2022-06-23 12:28
Bug confirmed

**Comment by mthh** [comment] 2022-08-31 15:21
Actually, I have a fix for this issue.

In fact, when we select "Lambert 93" in the "more options" menu (example 1), we use a projection managed by d3, using the bounds of the lambert-93 projection as the default zoom (well, a little wider than the bounds of lambert-93 actually).

When we select "Lambert 93" directly in the dropdown menu (example 2), we use a d3 projection created by us from the proj.4 definition of lambert 93 (and, more importantly, we try to use the bounds of the main layer, so here the whole world) as default zoom. In my case it doesn't log too much and it reprojects the map but it displays a background with many (if not only) artifacts.

I'm not going to push this fix right away because I want to check that there is no side effect (there was probably a reason for doing what we did so far...I have to make more tests).

I think one day we should discuss (@riatelab) what we should do about all the CRS that define bounds and do not apply globally.
Should we inform the user if these layers are outside these bounds (or not in them at all) ?
Should we cut out what is represented outside these bounds?

For example here, for lambert 93, the bug only occurs when using data that exceeds these bounds.

**Comment by mthh** [comment] 2024-07-04 18:06
Not relevant anymore.

**Closed by mthh** 2024-07-04 18:06 UTC
Labels: bug
